name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Create .env
      run: |
        touch .env &&
        echo "NODE_ENV=${NODE_ENV}" > .env &&
        echo "RTMP_PORT=${RTMP_PORT}" >> .env &&
        echo "RTMP_CHUNK_SIZE=${RTMP_CHUNK_SIZE}" >> .env &&
        echo "RTMP_GOP_CACHE=${RTMP_GOP_CACHE}" >> .env &&
        echo "RTMP_PING=${RTMP_PING}" >> .env &&
        echo "RTMP_PING_TIMEOUT=${RTMP_PING_TIMEOUT}" >> .env &&
        echo "PORT=${PORT}" >> .env &&
        echo "HTTP_ALLOW_ORIGIN=${HTTP_ALLOW_ORIGIN}" >> .env
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        RTMP_PORT: ${{ secrets.RTMP_PORT }}
        RTMP_CHUNK_SIZE: ${{ secrets.RTMP_CHUNK_SIZE }}
        RTMP_GOP_CACHE: ${{ secrets.RTMP_GOP_CACHE }}
        RTMP_PING: ${{ secrets.RTMP_PING }}
        RTMP_PING_TIMEOUT: ${{ secrets.RTMP_PING_TIMEOUT }}
        PORT: ${{ secrets.PORT }}
        HTTP_ALLOW_ORIGIN: ${{ secrets.HTTP_ALLOW_ORIGIN }}